apiVersion: v1
kind: Pod
metadata:
  name: netapp-pod
  namespace: netapp
spec:
  containers:
  - name: netapp-container
    image: artifactory.build.ingka.ikea.com/cloudenablement-docker-dev-local/orbit/alpine:1.0.0
    volumeMounts:
    - name: netapp-storage
      mountPath: /data
  volumes:
  - name: netapp-storage
    persistentVolumeClaim:
      claimName: netapp-test-pvc
