apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netapp-pvc
  namespace: netapp  
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 10Gi
  storageClassName: netapp-trident
