apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: netapp-trident
provisioner: csi.trident.netapp.io
mountOptions: 
  - nfsvers=3  
parameters:
  backendType: "ontap-nas-economy"
allowVolumeExpansion: true
volumeBindingMode: Immediate  
