apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netapp-test-pvc
  namespace: netapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-trident
