apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hs-storage
  dataSource:
    name: hammerspace-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
