apiVersion: v1
kind: Pod
metadata:
  name: restore-hammerspace-pod
  namespace: default
spec:
  containers:
  - name: restore-hammerspace-container
    image: artifactory.build.ingka.ikea.com/cloudenablement-docker-dev-local/orbit/alpine:1.0.0
    volumeMounts:
    - name: restored-hammerspace-storage
      mountPath: /data
    command: [ "sh", "-c", "sleep infinity"] #[ "ls", "-al", "/data" ]
  volumes:
    - name: restored-hammerspace-storage
      persistentVolumeClaim:
        claimName: restore-pvc
  imagePullSecrets:
    - name: image-pull-secret
