apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backendConfig.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}
