apiVersion: v1
kind: Pod
metadata:
  name: temp-shell-pod
  namespace: netapp
spec:
  containers:
  - name: shell
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: nfs-volume
      mountPath: /mnt/netapp-nfs
  volumes:
    - name: nfs-volume
      nfs:
       server: 172.23.246.31
       path: /trident_qtree_pool_trident_JBRHIOPECK

