apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: hammerspace-snapshot
  namespace: default
spec:
  volumeSnapshotClassName: hs-snapshots
  source:
    persistentVolumeClaimName: hammerspace-test-pvc
