apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.snapshotClass.name }}
driver: {{ .Values.snapshotClass.driver }}
deletionPolicy: {{ .Values.snapshotClass.deletionPolicy }}
